# Generated by Django 4.2.2 on 2023-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
